### ISSUE TITLE
Создание игры

### ISSUE THREAD

**Issue by mirrin00** [mirrin00/BugsMakers#7]
Создание необходимых классов игры и реализация их функционирования без логики всей игры

**Comment by aseleznyova** [comment]
* [ ] getHealth()
* [ ] getCoins()
* [ ] getMagic()
* [ ] getAttributes()
* [ ] getDescription()
* [ ] !a.active
* [ ] getActions()
* [ ] getInventory()
* [ ] getActiveItems()
* [ ] Картинки

**Comment by mirrin00** [comment]
* [ ] Game::sold(): добавить drop
* [ ] Во всех методах добавить view.update()
* [ ] Добавить изменение отрисовки деревьев(view.updateTree and view.updateLocalTree)

**Comment by mirrin00** [comment]
* [ ] Use to active items
* [ ] ПКМ - использовать, СКМ - выкинуть/продать

**Comment by mirrin00** [comment]
* [ ] Добавить картинки для игрока
* [ ] Ещё раз подумать о вставке картинки в кнопку
